### ISSUE TITLE
通过访问摄像头ip去监控摄像头是否可访问

### ISSUE THREAD

**Issue by peak-wind** [xinyiPig/zzx-hikvision-Java-demo#3]
![123](https://user-images.githubusercontent.com/72072249/99940778-d027f500-2da7-11eb-8fc4-a9d3413cc858.png)
这个定时器中
restTemplate.getForObject("http://" + ip, String.class);
这个会有问题吧，channelName 随便传，但是这个执行就报错了

**Comment by zzx-Pillar** [comment]
不是传channelName，传的是摄像头ip地址

**Comment by peak-wind** [comment]
@ApiOperation(value = "windows 获取实时视频流", notes = "channelStream:101 代表通道一 主码流。102代表通道一 子码流；子码流比主码流小，但画质会有所下降 ，channelName是通道名，能保证唯一即可")

manager.start(channelName,XX);

那这个方法有点误导，这个用的就是channelName

**Comment by zzx-Pillar** [comment]
哈哈哈，确实是有点误导了，增加这个KillTask的时候跟前端同事约定 channleName直接传ip，这样也能保证不重复，没做好记录，抱歉抱歉
