### ISSUE TITLE
question:项目运行无报错信息，但是视频输出

### ISSUE THREAD

**Issue by wimmerX** [xinyiPig/zzx-hikvision-Java-demo#4]
os:linux
jvm:1.8
status:控制台使用ffmpeg命令执行rtsp->rtmp,使用vlc可以看到视频。但是测试了贵项目，无报错信息，但是也看不到视频。怀疑可能是程序的命令行没有运行，在cli使用ps -ef|grep ffmpeg确实没有看到线程.请问，这可能的原因是什么呢？谢谢

**Comment by wimmerX** [comment]
resolve: `String[] cmd = new String[]{"sh", "-c", str};
		Process process = Runtime.getRuntime().exec(cmd);`

**Comment by zzx-Pillar** [comment]
要在linux上装一个ffmpeg再加个x264的码流转换器





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mohist ***@***.***&gt;
发送时间: 2021年3月17日 11:35
收件人: xinyiPig/zzx-hikvision-Java-demo ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[xinyiPig/zzx-hikvision-Java-demo] question:项目运行无报错信息，但是视频输出 (#4)





 
os:linux
 jvm:1.8
 status:控制台使用ffmpeg命令执行rtsp-&gt;rtmp,使用vlc可以看到视频。但是测试了贵项目，无报错信息，但是也看不到视频。怀疑可能是程序的命令行没有运行，在cli使用ps -ef|grep ffmpeg确实没有看到线程.请问，这可能的原因是什么呢？谢谢

**Comment by wimmerX** [comment]
> 要在linux上装一个ffmpeg再加个x264的码流转换器 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Mohist ***@***.***&gt; 发送时间: 2021年3月17日 11:35 收件人: xinyiPig/zzx-hikvision-Java-demo ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[xinyiPig/zzx-hikvision-Java-demo] question:项目运行无报错信息，但是视频输出 (#4) os:linux jvm:1.8 status:控制台使用ffmpeg命令执行rtsp-&gt;rtmp,使用vlc可以看到视频。但是测试了贵项目，无报错信息，但是也看不到视频。怀疑可能是程序的命令行没有运行，在cli使用ps -ef|grep ffmpeg确实没有看到线程.请问，这可能的原因是什么呢？谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ffmpeg不就可以转码么？再装一个x264转换器是什么目的呢？另外，我现在没装x264是可以运行，并且能够看到画面，但是延迟较高，是带宽的问题么？

**Comment by zzx-Pillar** [comment]
不用装码流转换也能运行吗？可能你装的是新版ffmpeg，自带码流转换工具。海康摄像头的视频流一般是通过转换器转换成h264或者h265，这两种视频格式可以百度一下哈，另外延迟高可能有两个原因：1、输出的分辨率太高了，适当降低一点。2、摄像头的rstp码流有两种，主码流和子码流，主码流清晰质量高，子码流模糊质量偏差，你可以切换为子码流试试

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mohist ***@***.***&gt;
发送时间: 2021年3月17日 13:50
收件人: xinyiPig/zzx-hikvision-Java-demo ***@***.***&gt;
抄送: xinyiPig ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[xinyiPig/zzx-hikvision-Java-demo] question:项目运行无报错信息，但是视频输出 (#4)





 
ffmpeg不就可以转码么？再装一个x264转换器是什么目的呢？另外，我现在没装x264是可以运行，并且能够看到画面，但是延迟较高，是带宽的问题么？
